development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: hybrid_development
  pool: 5
  username: devuser
  password: devpass
  host: 127.0.0.1

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: hybrid_test
  pool: 5
  username: devuser
  password: devpass
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: hybrid_production
  pool: 5
  username: user
  password: -wee
  host: 127.0.0.1
